DISCOVERY_SEED_KEYWORDS = [
    "tea",
    "snack",
    "drink",
    "dessert",
    "recipe",
    "functional beverage",
    "healthy snack",
    "protein snack",
    "prebiotic soda",
    "gut health drink",
    "adaptogen drink",
    "energy drink",
    "hydration drink",
    "sparkling water",
    "wellness shot",
    "protein bar",
    "granola",
    "cookies",
    "candy",
    "frozen dessert",
    "matcha",
    "ginseng",
    "turmeric",
    "ginger",
    "kombucha",
    "mushroom coffee",
    "electrolyte drink",
    "probiotic drink",
    "superfood powder",
    "plant based snack",
    "plant based milk",
    "protein shake",
    "cereal bar",
    "hydration powder",
    "energy bites",
    "fruit snack",
    "iced tea",
    "cold brew",
    "olive oil",
    "hot sauce",
    "salsa",
    "ramen",
    "kimchi",
    "yogurt drink",
    "smoothie bowl",
    "cookie dough",
    "chili crisp",
    "black garlic",
    "freeze dried candy",
    "freeze dried fruit",
    "dumplings",
    "ramen bowl",
    "vinegar drink",
    "balsamic vinegar",
    "sea moss drink",
    "tallow",
    "beef tallow",
    "konjac noodles",
    "cassava chips",
    "miso soup",
    "gochujang sauce",
    "szechuan snack",
    "hot honey snack",
]


INGREDIENT_TERMS = [
    "acai",
    "acerola",
    "adaptogen",
    "agave",
    "algae",
    "allulose",
    "almond",
    "aloe vera",
    "amla",
    "anise",
    "apple",
    "apple cider vinegar",
    "apricot",
    "arabica",
    "argan oil",
    "artichoke",
    "aspartame",
    "ashwagandha",
    "asparagus",
    "avocado oil",
    "banana",
    "barley",
    "basil",
    "beet",
    "black pepper",
    "biotin",
    "black tea",
    "black garlic",
    "bone broth",
    "bovine collagen",
    "bran",
    "broccoli",
    "brown rice",
    "buckwheat",
    "cacao",
    "caffeine",
    "calcium",
    "calendula",
    "camelina oil",
    "cane sugar",
    "capsaicin",
    "cardamom",
    "carrageenan",
    "cashew",
    "casein",
    "cayenne",
    "celery",
    "chamomile",
    "chia",
    "chicory root",
    "chili",
    "chlorophyll",
    "chromium",
    "clove",
    "cinnamon",
    "citrus",
    "citric acid",
    "coconut",
    "coconut water",
    "cornichon",
    "collagen",
    "collagen peptides",
    "coriander",
    "corn",
    "cranberry",
    "creatine",
    "curcumin",
    "dates",
    "dextrose",
    "dragon fruit",
    "durian",
    "electrolyte",
    "elderberry",
    "enzyme",
    "erythritol",
    "fonio",
    "fennel",
    "fiber",
    "fig",
    "flax",
    "folate",
    "garlic",
    "gellan gum",
    "ginger",
    "ginseng",
    "glucomannan",
    "glucose",
    "glutamine",
    "goji",
    "grape",
    "green tea",
    "greens powder",
    "guarana",
    "guar gum",
    "hemp",
    "honey",
    "hops",
    "horchata",
    "jalapeno",
    "inulin",
    "isolate protein",
    "jasmine",
    "kava",
    "kiwi",
    "l theanine",
    "lavender",
    "lecithin",
    "lemon",
    "lime",
    "lion's mane",
    "maca",
    "malic acid",
    "magnesium",
    "mango",
    "mct oil",
    "melatonin",
    "maple syrup",
    "matcha",
    "melon",
    "menthol",
    "millet",
    "milk protein",
    "monk fruit",
    "moringa",
    "mushroom",
    "nutmeg",
    "nootropics",
    "olive",
    "oatmilk",
    "olive oil",
    "omega 3",
    "onion",
    "orange",
    "oregano",
    "paprika",
    "parsley",
    "passion fruit",
    "pea protein",
    "pectin",
    "peppermint",
    "pineapple",
    "pink salt",
    "piri piri",
    "pickle brine",
    "polyphenols",
    "potassium",
    "pomegranate",
    "prickly pear",
    "pumpkin seed",
    "prebiotic",
    "probiotic",
    "protein",
    "psyllium",
    "quinoa",
    "raspberry",
    "reishi",
    "rosemary",
    "rocoto",
    "saffron",
    "sage",
    "sesame",
    "szechuan peppercorn",
    "sea moss",
    "sea salt",
    "seaweed",
    "sherry vinegar",
    "selenium",
    "shiitake",
    "soy",
    "sodium",
    "sourdough starter",
    "soy protein",
    "spirulina",
    "strawberry",
    "stevia",
    "superfood",
    "sunflower oil",
    "sweet potato",
    "tapioca",
    "tamarind",
    "taurine",
    "thyme",
    "tomato",
    "truffle",
    "turmeric",
    "vanilla",
    "vanilla bean",
    "vinegar",
    "walnut",
    "watermelon",
    "wheat",
    "vitamin b12",
    "vitamin c",
    "vitamin d",
    "water lentils",
    "xylitol",
    "whey protein",
    "xanthan gum",
    "yuzu",
    "yerba mate",
]


ADDITIVE_TERMS = [
    "acesulfame potassium",
    "acidulant",
    "annatto",
    "artificial sweetener",
    "ascorbic acid",
    "balsamic glaze",
    "blue 1",
    "blue 2",
    "calcium carbonate",
    "calcium propionate",
    "cane sugar",
    "caramel color",
    "cellulose gum",
    "citric acid",
    "corn syrup",
    "dairy free creamer",
    "dextrose",
    "disodium phosphate",
    "emulsifier",
    "erythritol",
    "flavoring",
    "fructose",
    "gellan gum",
    "gum arabic",
    "guar gum",
    "high fructose corn syrup",
    "invert sugar",
    "lactic acid",
    "lecithin",
    "maltodextrin",
    "modified corn starch",
    "modified starch",
    "monk fruit",
    "natural flavors",
    "pickle flavoring",
    "preservative",
    "propylene glycol",
    "pectin",
    "polysorbate 80",
    "potassium sorbate",
    "rice syrup",
    "red 40",
    "silicon dioxide",
    "sorbic acid",
    "sodium benzoate",
    "stabilizer",
    "soy lecithin",
    "stevia",
    "sucralose",
    "sugar alcohol",
    "tbhq",
    "thickener",
    "titanium dioxide",
    "tocopherols",
    "xanthan gum",
    "yeast extract",
    "yellow 5",
    "yellow 6",
]


PRODUCT_FORMAT_TERMS = [
    "aioli",
    "bar",
    "boba",
    "beverage",
    "biscuit",
    "bites",
    "bowl",
    "broth",
    "brownie",
    "burger",
    "candy",
    "cereal bar",
    "capsule",
    "cereal",
    "chews",
    "chips",
    "chutney",
    "coffee",
    "cookie",
    "cracker",
    "cream",
    "creamer",
    "dessert",
    "dip",
    "drink",
    "dressing",
    "elixir",
    "gel",
    "gelato",
    "granola",
    "gum",
    "gummies",
    "ice cream",
    "juice",
    "jerky",
    "latte",
    "lemonade",
    "loaf",
    "mix",
    "mocktail",
    "noodles",
    "oatmeal",
    "pasta",
    "pastry",
    "popsicle",
    "powder",
    "pudding",
    "recipe",
    "roll",
    "sauce",
    "seasoning",
    "seltzer",
    "shake",
    "shot",
    "smoothie",
    "snack",
    "soda",
    "soup",
    "sparkling water",
    "supplement",
    "syrup",
    "tea",
    "tonic",
    "trail mix",
    "wafer",
    "water",
    "wellness shot",
    "wrap",
    "yogurt",
    "vinaigrette",
]


FOOD_TERMS = sorted(
    set(
        DISCOVERY_SEED_KEYWORDS
        + INGREDIENT_TERMS
        + ADDITIVE_TERMS
        + PRODUCT_FORMAT_TERMS
        + [
            "almond butter",
            "applesauce",
            "bagel chips",
            "baklava",
            "banana bread",
            "bbq sauce",
            "beef jerky",
            "boba",
            "bone broth protein",
            "bread",
            "breadsticks",
            "brioche",
            "brittle",
            "buldak",
            "burrito bowl",
            "butter",
            "butter board",
            "caesar dressing",
            "cake",
            "candy bar",
            "cappuccino",
            "caramel popcorn",
            "cassava chips",
            "cereal bar",
            "chai",
            "charcuterie",
            "cheese",
            "cheese crisps",
            "cheesecake",
            "chia pudding",
            "chicken broth",
            "chickpea puffs",
            "chili crisp",
            "chocolate",
            "chocolate milk",
            "chocolate spread",
            "churro",
            "coconut yogurt",
            "cold brew",
            "cookies and cream",
            "cookie dough",
            "cottage cheese",
            "cream soda",
            "cream cheese",
            "croissant",
            "cupcake",
            "custard",
            "danish",
            "dessert tea",
            "dip mix",
            "donut",
            "dosa",
            "dumplings",
            "electrolyte mix",
            "empanada",
            "energy bites",
            "energy drink",
            "english muffin",
            "falafel",
            "fermented foods",
            "flavored water",
            "flatbread",
            "freeze dried candy",
            "freeze dried cheesecake bites",
            "freeze dried fruit",
            "focaccia",
            "frozen yogurt",
            "fruit snack",
            "fruit leather",
            "fudge",
            "gelato",
            "gluten free bread",
            "granola butter",
            "green juice",
            "grilled cheese",
            "gummies",
            "harissa cheese bites",
            "harissa",
            "herbal tea",
            "honey mustard",
            "hot honey",
            "hot sauce",
            "hummus",
            "ice cream",
            "iced tea",
            "instant noodles",
            "isotonic drink",
            "jam",
            "jerky",
            "juice shot",
            "kefir",
            "kimchi",
            "konjac noodles",
            "korean corn dog",
            "latte mix",
            "lemon water",
            "lemonade",
            "mac and cheese",
            "marshmallow",
            "meal replacement",
            "meal shake",
            "milkshake",
            "miso",
            "miso ramen",
            "muffin",
            "nut butter",
            "oatmeal",
            "olive oil cake",
            "pancake mix",
            "pasta",
            "pesto",
            "pickles",
            "pickle chips",
            "plant based milk",
            "plantain chips",
            "popcorn",
            "popsicle",
            "pretzel",
            "pretzel bites",
            "protein balls",
            "protein chips",
            "protein cookie",
            "protein pasta",
            "protein shake",
            "protein pudding",
            "protein water",
            "ramune",
            "ramen",
            "rice cake",
            "rice crackers",
            "salad dressing",
            "salsa",
            "salsa macha",
            "sandwich cookie",
            "sauce",
            "seasoning blend",
            "sea moss gummies",
            "seed crackers",
            "shake mix",
            "shelf stable milk",
            "slushie",
            "smoothie bowl",
            "soda water",
            "sorbet",
            "soup",
            "sour candy",
            "sparkling juice",
            "sparkling tea",
            "sports drink",
            "sriracha",
            "stuffed pretzel",
            "supplement drink",
            "sweet tea",
            "sweet potato chips",
            "tallow fries",
            "taco sauce",
            "tea latte",
            "toaster pastry",
            "tofu",
            "tonic water",
            "tomato soup",
            "trail mix",
            "truffle sauce",
            "vinegar tonic",
            "vinaigrette salad kit",
            "vegetable chips",
            "vanilla yogurt",
            "vitamin water",
            "wafer",
            "water enhancer",
            "whipped coffee",
            "wellness beverage",
            "wellness tonic",
            "wrap",
            "yogurt drink",
            "yogurt parfait",
            "yuzu vinaigrette",
        ]
    )
)


NOISE_PATTERNS = [
    "amazon prime",
    "celebrity",
    "instagram",
    "lyrics",
    "movie",
    "news",
    "reddit",
    "show",
    "song",
    "stock",
    "target",
    "tiktok",
    "walmart",
    "youtube",
]
