"""
temporary_demo_data.py: Mock Data Provider

Provides mock API responses for Google Trends and Amazon Bestsellers to allow offline
development and UI testing without consuming API credits or requiring network connectivity.
"""
TEMPORARY_GOOGLE_TRENDS_RECORDS = [
    {
        "query": "matcha gummies",
        "source_seed": "matcha",
        "intent_bucket": "eat_or_buy",
        "trend_type": "ingredient",
        "market_signal": "commercial_demand",
        "popularity_score": 87,
        "search_growth": 240,
        "trend_velocity": 91.5,
        "opportunity_score": 107.1,
    },
    {
        "query": "prebiotic soda",
        "source_seed": "prebiotic soda",
        "intent_bucket": "eat_or_buy",
        "trend_type": "product_format",
        "market_signal": "commercial_demand",
        "popularity_score": 93,
        "search_growth": 320,
        "trend_velocity": 100.0,
        "opportunity_score": 115.8,
    },
    {
        "query": "sea moss drink",
        "source_seed": "sea moss drink",
        "intent_bucket": "learn",
        "trend_type": "ingredient",
        "market_signal": "consumer_education",
        "popularity_score": 72,
        "search_growth": 210,
        "trend_velocity": 65.6,
        "opportunity_score": 65.36,
    },
    {
        "query": "protein pudding",
        "source_seed": "protein shake",
        "intent_bucket": "eat_or_buy",
        "trend_type": "product_format",
        "market_signal": "commercial_demand",
        "popularity_score": 69,
        "search_growth": 180,
        "trend_velocity": 56.2,
        "opportunity_score": 75.12,
    },
    {
        "query": "hot honey snack",
        "source_seed": "hot honey snack",
        "intent_bucket": "eat_or_buy",
        "trend_type": "ingredient",
        "market_signal": "commercial_demand",
        "popularity_score": 76,
        "search_growth": 195,
        "trend_velocity": 60.9,
        "opportunity_score": 82.14,
    },
    {
        "query": "vinegar drink",
        "source_seed": "vinegar drink",
        "intent_bucket": "learn",
        "trend_type": "ingredient",
        "market_signal": "consumer_education",
        "popularity_score": 58,
        "search_growth": 165,
        "trend_velocity": 51.5,
        "opportunity_score": 51.06,
    },
]


TEMPORARY_AMAZON_TRENDS_RECORDS = [
    {
        "query": "matcha gummies",
        "source_seed": "matcha gummies",
        "amazon_market_signal": "emerging_opportunity",
        "amazon_popularity_score": 640.0,
        "amazon_trend_velocity": 84.2,
        "amazon_opportunity_score": 80.1,
        "avg_price": 18.99,
        "food_relevant": True,
    },
    {
        "query": "prebiotic soda",
        "source_seed": "prebiotic soda",
        "amazon_market_signal": "established_market",
        "amazon_popularity_score": 4200.0,
        "amazon_trend_velocity": 88.7,
        "amazon_opportunity_score": 62.4,
        "avg_price": 26.5,
        "food_relevant": True,
    },
    {
        "query": "protein pudding",
        "source_seed": "protein pudding",
        "amazon_market_signal": "emerging_opportunity",
        "amazon_popularity_score": 510.0,
        "amazon_trend_velocity": 81.3,
        "amazon_opportunity_score": 78.6,
        "avg_price": 14.75,
        "food_relevant": True,
    },
    {
        "query": "hot honey snack",
        "source_seed": "hot honey snack",
        "amazon_market_signal": "niche_market",
        "amazon_popularity_score": 290.0,
        "amazon_trend_velocity": 57.8,
        "amazon_opportunity_score": 61.9,
        "avg_price": 11.4,
        "food_relevant": True,
    },
]
